### ISSUE TITLE
returnEval doesn't work

### ISSUE THREAD

**Issue by avishayil** [greatbsky/react-native-webview2#1]
Hi, I tried to download the sample app but pressing on the Get Title doesn't work.
On Safari, while debugging the page, there is no returnEval function at all, and even manually declaring it doesn't link to the RN component.

**Comment by greatbsky** [comment]
`<Web  evalReturn={this.evalReturn}  source={{uri: 'http://www.baidu.com'}} ....../>`
make sure you can visit the web page **http**://www.baidu.com on your device, otherwise you can modify the url.
The returnEval function is in the web page of webview, not in reactnative.
you can try modify this code in the sample app:
`
test() {
        this.web.evalJs('alert(returnEval)');
    }
`

**Comment by rrrrrrex** [comment]
I have the same question.

Uncaught ReferenceError: returnEval is not defined

**Comment by greatbsky** [comment]
@darkguy405 @avishayil hi, can you post your code and upload the capture of error here?
you should know:
this.web.evalJs('.....returnEval in string'), returnEval is in string, it's just a js function in webview html page.

**Comment by rrrrrrex** [comment]
i didn't use 'this.web.evalJs('.....returnEval in string')', i want webpage to pass some value to react-native.

in webpage:

   function sendpoi(){
      returnEval('this.callback("' + JSON.stringify(sendObj) + '")');
   }

**Comment by greatbsky** [comment]
make sure you call sendpoi() after window.onload.

**Comment by rrrrrrex** [comment]
sure,should i import some js about 'returnEval()' in webpage?

Uncaught ReferenceError: returnEval is not defined

**Comment by greatbsky** [comment]
加QQ=parseInt('110101001110010000011111000110', 2);

**Comment by greatbsky** [comment]
can you  try this? @darkguy405 
`
<script>
document.body.onclick = function(){
    alert(returnEval)
}
<script>
`
you should see a alert after click the webpage.

**Comment by darkguy405** [comment]
same error

Uncaught ReferenceError: returnEval is not defined

**Comment by rrrrrrex** [comment]
yes.it show 'function(v){window.loaction.hash=0.6.....(string(v))}'

**Comment by greatbsky** [comment]
so I think you called js before create returnEval function, **returnEval** function will be assigned to window after the webpage loaded.
If you need call **returnEval** after webpage loaded, you can use setInterval. then clearInterval when window.returnEval existed.

**Comment by rrrrrrex** [comment]
@greatbsky  now i can use **returnEval** funcion. but my 'returnEval('this.callback("test")');' didn't work.

undefined is not a function (evaluating 'this.callback("test")')

**Comment by greatbsky** [comment]
you should set property `evalReturn={(r) => {eval(r)}` in the component which bind  `this.callback` function.

**Comment by rrrrrrex** [comment]
render() {
     return  <Web
               style={{ flex: 1, width: width }}
               ref={(c) => { this.web = c } }
               evalReturn={(r) => { eval(r) } }
              javaScriptEnabled={true}
              source={{ uri: Config.MAPURL }}/>
  }

  callback(message) {
    Alert.alert('',message);
}

this is my code ,the error catch at 'evalReturn={(r) => { eval(r) } }'

**Comment by greatbsky** [comment]
sorry, The correct code is:

```
...
evalReturn={((r) => {eval(r)}).bind(this)}
...
```

I have modify the document, thanks.

**Comment by rrrrrrex** [comment]
@greatbsky oh i see, it can work now,thanks.

**Comment by greatbsky** [comment]
welcome
