### ISSUE TITLE
returnEval只能执行一次

### ISSUE THREAD

**Issue by xuanheScript** [greatbsky/react-native-webview2#11]
ios下(android没有测试)，在html中使用onclick="returnEval('this.func();')" 
html中多个按钮，同一按钮点击2次以上不执行natvie方法,点击一个其他按钮后，再点之前的就正常了。

**Comment by greatbsky** [comment]
新发布了version 1.1.1，应该没有问题了

**Comment by xuanheScript** [comment]
好的，辛苦
