### ISSUE TITLE
为什么不支持html啊

### ISSUE THREAD

**Issue by mvpdream** [greatbsky/react-native-webview2#2]
rt 
source={{html:xxx}}就像这样

**Comment by greatbsky** [comment]
要实现高度自适应autoheight及js相互调用call js可以直接在source={{html:xxx}}的html内容里改变title实现，目前精力有限，本组件暂支持source={uri:xxx}，以后会考虑支持source={{html:xxx}}，请见谅~~~

**Comment by mvpdream** [comment]
方便给个微信或者qq吗  请教一下

**Comment by greatbsky** [comment]
ok, Q=parseInt('110101001110010000011111000110', 2);，我把这个issue关了~~
