### ISSUE TITLE
autoHeight Don't work on iOS

### ISSUE THREAD

**Issue by hujiudeyang** [greatbsky/react-native-webview2#3]

**Comment by greatbsky** [comment]
please post your code & screen capture

**Comment by tioback** [comment]
For me, it isn't working on iOS, but Android is OK.
I used the code provided in the [demo](https://github.com/greatbsky/react-native-webview2-demo).

![simulator screen shot 7 de set de 2016 02 34 54](https://cloud.githubusercontent.com/assets/13951017/18300972/1ddaee2c-74a4-11e6-9c3f-c0f13a89c1fd.png)

**Comment by tioback** [comment]
@greatbsky please let me know if I can help on fixing this.

**Comment by greatbsky** [comment]
@tioback sorry for waiting, I have tell someone to fix this....

**Comment by greatbsky** [comment]
@tioback @hujiudeyang thanks for your report, Auto height should be supported on ios from version 1.0.3, if you still have problem , tell me please ~~

**Comment by greatbsky** [comment]
sorry, still not work, I will modify the day after tomorraw

**Comment by tioback** [comment]
@greatbsky - it worked for me in RN 0.34.0 and react-native-webview2 1.0.3 🤔

**Comment by greatbsky** [comment]
@tioback is it on ios?

**Comment by tioback** [comment]
Yeah, iOS sometimes works, sometimes doesn't.
Android was working, but now stopped. I must have done something that messed it up.

**Comment by greatbsky** [comment]
@tioback hi, react-native-webview2 of version 1.0.4 have supported autoheight on ios.
so I close this issue.
