### ISSUE TITLE
demo中点击Get Title Button没反应

### ISSUE THREAD

**Issue by loren325** [greatbsky/react-native-webview2#6]
setText方法没有执行

**Comment by greatbsky** [comment]
什么平台？支持android，ios暂不支持，还需要等页面加载完才可以

**Comment by loren325** [comment]
android的

**Comment by greatbsky** [comment]
需要等页面加载完，如果还不行，建议debug调试看有没有出什么错误信息？

**Comment by loren325** [comment]
我用MX5手机没有反应，用华为手机就可以，这个还跟设备有关？

**Comment by greatbsky** [comment]
那你重新创建个demo，把src的代码copy过去试试吧~~按理说跟设备没关系

**Comment by yulianger** [comment]
似乎就是和设备有关。。。

**Comment by greatbsky** [comment]
新发布了version 1.1.1，没有发现问题，有问题再反馈
