### ISSUE TITLE
安卓小米手机为啥不能自动高度

### ISSUE THREAD

**Issue by yulianger** [greatbsky/react-native-webview2#7]
有些安卓手机为啥不能自动高度？

**Comment by greatbsky** [comment]
貌似跟系统版本有关~~~建议更新到最新版RN
可以尝试下 使用webview调用injectjavascript方法是否可以执行？

**Comment by greatbsky** [comment]
发布了新版version1.1.1，可以自动高度了，有问题再反馈！
