### ISSUE TITLE
react-native 0.37高度无法自适应，并且height属性无效

### ISSUE THREAD

**Issue by xuanheScript** [greatbsky/react-native-webview2#8]
style中height设置无效,没有任何高度显示，自适应也无高度显示，只有minHeight设置才有效

**Comment by greatbsky** [comment]
我明后天看看~~~

**Comment by greatbsky** [comment]
@xuanheScript RN0.37.0测试过了，height是可以设置的，设置后固定高度，取消height高度可以自适应。
你可以尝试重新run试试

**Comment by zongxiaomi** [comment]
请问能支持 html代码块吗 比如 ,<p>test<p/> <img src="img.ff.com"> 等代码块  现在有个需求是服务器返回了字符串形式的代码块

**Comment by zongxiaomi** [comment]
没显示出来 重新贴一下  **"<p>test</p> <img src=""/>"**

**Comment by zongxiaomi** [comment]
"<p>test</p> <img src=""/>"

**Comment by zongxiaomi** [comment]
`"<p>test</p> <img src=""/>"`

**Comment by greatbsky** [comment]
sorry，不支持html代码块的~~~@zongxiaomi

**Comment by greatbsky** [comment]
发布了新版version1.1.1，可以自动设置height了，有问题再反馈吧
