### ISSUE TITLE
打开 一些页面 空白哦

### ISSUE THREAD

**Issue by zanjs** [greatbsky/react-native-webview2#9]
比如 打卡 http://gold.xitu.io/user/settings 会空白

**Comment by greatbsky** [comment]
你好，我发现你这个url会自动跳转，会不会跟js有关系？webview2是基于webview的，如空白替换为webview看看是否也空白？

**Comment by zanjs** [comment]
使用 `webview`  没问题的 ，最终还是换回 `webview`
